#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Rodar o phpstan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Corrija os erros do phpstan antes de commitar...";
    exit 1;
fi;

# Rodar os testes
php artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo "Corrija os erros dos testes antes de commitar...";
    exit 1;
fi;

# Formata os arquivos que estão sendo commitados usando o Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;

exit 0;